### ISSUE TITLE
Hook IDE plugin into formatting action

### ISSUE THREAD

**Issue by tnorbye** [tnorbye/kdoc-formatter#12]
Right now formatting in the IDE plugin is done via a separate action (Code > Reformat KDoc). It would be nice if we could hook this into the IDE's native formatting action (Code > Reformat Code) instead. Investigate whether it's possible to register as a formatting participant.

**Comment by lppedd** [comment]
Hi @tnorbye, you can definitely use a `PostFormatProcessor` for this.

**Comment by tnorbye** [comment]
This is now fixed in v1.4.0.
