### ISSUE TITLE
Empty lines in preformatted paragraphs

### ISSUE THREAD

**Issue by vmassaro** [tnorbye/kdoc-formatter#23]
Hi Tor! 

First of all, thank you for making this tool available! :D
I tried it today as a Gradle Plugin and it works amazing!

I only had one issue with it: when there is some preformatted paragraph (in my case a code block) with an empty line in it, the tool will add (or leave there if already present) a trailing space. While this is not necessarily bad per se, it conflicts with Ktlint `no-trailing-spaces` rule.

Specifically, if you have a KDoc with a code snippet as follows:

```
/**
 * ```kotlin
 * val myValue: Any = get()
 * 
 * fun myFun() = Unit
 * ```
 */
```

Ktlint will try and remove the trailing space from the empty line in between `val` and `fun`, while kdoc-formatter will add it back.

I took a quick look and will send out a PR that I think should fix the issue.

Please let me know if what I did makes sense :)

Thanks!

**Comment by tnorbye** [comment]
Thanks! Right now kdoc-formatter tries to not touch any of the text in fenced blocks (```) since it assumes those are preformatted and things like trailing lines (in theory) should be supported, but I suspect in practice everybody wants these removed. Thanks again for the PR!

**Comment by vmassaro** [comment]
Yeah, I agree, in principle trailing lines in code blocks shouldn't be an issue, perhaps ktlint is not trying to parse them, and just checks for trailing spaces line by line, no matter what 🤷 

Anyway, thanks for accepting the change and, again, for making the tool available! :D

Closing this!
