### ISSUE TITLE
Reformat breaks nested bulleted lists.

### ISSUE THREAD

**Issue by wfhartford** [tnorbye/kdoc-formatter#36]
Kdoc such as the following:
```
/**
 * Paragraph
 * * Top Bullet
 *    * Sub-Bullet
 */
```
Would normally be rendered as:

> Paragraph
> * Top Bullet
>     * Sub-Bullet

This plugin will reformat the documentation as follows:
```
/**
 * Paragraph
 * * Top Bullet
 * * Sub-Bullet
 */
```
This significantly changes the markdown rendering of the comment:
> Paragraph
> * Top Bullet
> * Sub-Bullet

**Comment by tnorbye** [comment]
Fixed in 1.4.1. Thanks for the report. (The IDE plugin is pending review in the plugin portal.)
