### ISSUE TITLE
Multi asterisk removal (stability)

### ISSUE THREAD

**Issue by davidtorosyan** [tnorbye/kdoc-formatter#60]
This removes a `*` every time it formats
 
Before:
```kt
/** *** Testing */
fun foo() = Unit
```
 
After:
```kt
/** ** Testing */
fun foo() = Unit
```
 
After (again):
```kt
/** * Testing */
fun foo() = Unit
```
 
When using default options on v1.5.1.

**Comment by tnorbye** [comment]
This is fixed in 1.5.4 (released just now).
