### ISSUE TITLE
Preserve newline style

### ISSUE THREAD

**Issue by davidtorosyan** [tnorbye/kdoc-formatter#76]
Formatter should preserve newline style.
 
Before:
```kt
/**
 * Sample summary.
 *
 * More summary.
 */
fun foo() = Unit
```
 
In VS Code, switch from "LF" to "CRLF" on the bottom right.
 
Run the formatter with v1.5.5 with default options, and it formats the newlines it changes back to LF.

**Comment by tnorbye** [comment]
This should be fixed in 1.5.7.
