### ISSUE TITLE
[Feature Request] Replace `{@param name}` with `[name]`

### ISSUE THREAD

**Issue by davidtorosyan** [tnorbye/kdoc-formatter#79]
I see this pattern, copied from Java.

Before:
```kt
/**
 * Some summary.
 *
 * Another summary about {@param someParam}.
 */
fun foo() = Unit
```

Here's my requested output:
```kt
/**
 * Some summary.
 *
 * Another summary about [someParam].
 */
fun foo() = Unit
```

There are some other patterns like `{@code`, `{@see`, `{@attr-name`, `{@inheritDoc}`, but I'm not sure how to handle all of them.

Tested with v1.5.5 using default options.

**Comment by tnorbye** [comment]
This should be implemented in 1.5.7.
