### ISSUE TITLE
Add license headers to source files

### ISSUE THREAD

**Issue by nreid260** [tnorbye/kdoc-formatter#82]
The text of the Apache license says that to apply it to code, the code should carry a license header. The files in /library don't, so it's unclear what the copyright situation is.

**Comment by tnorbye** [comment]
Fixed with https://github.com/tnorbye/kdoc-formatter/commit/b5bff83a647e6198d198dbcf84e9e273a37d8c90

**Comment by nreid260** [comment]
Thanks!
