### ISSUE TITLE
Comment breaking isn't idempotent

### ISSUE THREAD

**Issue by ColtonIdle** [tnorbye/kdoc-formatter#97]
Curious if this is better suited to be ported from ktfmt (which uses kdoc-formatter) to kdoc-formatter: https://github.com/facebook/ktfmt/issues/438

**Comment by hick209** [comment]
I can attest that if we "turn off" kdoc in ktfmt, the issue referred on https://github.com/facebook/ktfmt/issues/438 stops happening

**Comment by hick209** [comment]
TBH it is possible we are using it wrong somehow.
I'm familiar with it yet and just did some crude investigation, but here's how I turned it off

Changed here to to always return the original text
https://github.com/facebook/ktfmt/blob/main/core/src/main/java/com/facebook/ktfmt/kdoc/KDocCommentsHelper.kt#L43-L46

Basically this:
```
if (!tok.isComment || true) {
  return tok.originalText
}
...
```

**Comment by tnorbye** [comment]
Ah, thanks. Yeah, that class (`KDocCommentsHelper`) isn't part of kdoc-formatter; it's a class added by ktfmt when kdoc-formatter was integrated into ktfmt; it's where they hook up their AST representation to do comment formatting. And if you look at that file, you can see that only kdoc comments are formatted with kdoc formatter (line 49); line comments are just formatted by the `indentLineComments` method, also implemented in that same class (line 96 and line 107).

**Comment by hick209** [comment]
Oh, good call out! Thanks a ton for pointing it to me, it saved me some tinkering time for sure.

It looks to me like it should be safe to close this issue then as it is indeed a ktfmt thing. I'll leave that up to you though.

**Comment by tnorbye** [comment]
Thanks! Sorry I didn't notice this issue earlier!
